name: Deploy on AWS EC2

on:
  push:
    branches:
      - ec2-deploy
    paths:
      - "server/**"

defaults:
  run:
    working-directory: "server"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Private Key
        run: |
          mkdir ~/.ssh/
          echo "${{secrets.MY_PRIVATE_KEY}}" > ~/.ssh/video-key.pem
          chmod 400 ~/.ssh/video-key.pem

      - name: SSH to EC2 && Pull && Install New Dependencies && Restart
        run: |
          ssh -i "~/.ssh/video-key.pem" -o StrictHostKeyChecking=no ec2-user@ec2-18-206-154-3.compute-1.amazonaws.com << EOF
            sudo yum update
            sudo su -
            cd Video-Hub/server
            git pull
            npm install
            pm2 restart all
          EOF
